# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from githubpb import github_pb2 as githubpb_dot_github__pb2


class GithubServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFollowers = channel.unary_unary(
        '/github.GithubService/GetFollowers',
        request_serializer=githubpb_dot_github__pb2.FollowerRequest.SerializeToString,
        response_deserializer=githubpb_dot_github__pb2.FollowerResponse.FromString,
        )


class GithubServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFollowers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GithubServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFollowers': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowers,
          request_deserializer=githubpb_dot_github__pb2.FollowerRequest.FromString,
          response_serializer=githubpb_dot_github__pb2.FollowerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'github.GithubService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
