// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.proto

package githubp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FollowerRequest struct {
	GithubUsername       string   `protobuf:"bytes,1,opt,name=github_username,json=githubUsername,proto3" json:"github_username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowerRequest) Reset()         { *m = FollowerRequest{} }
func (m *FollowerRequest) String() string { return proto.CompactTextString(m) }
func (*FollowerRequest) ProtoMessage()    {}
func (*FollowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7664b366d7fb87ed, []int{0}
}

func (m *FollowerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerRequest.Unmarshal(m, b)
}
func (m *FollowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerRequest.Marshal(b, m, deterministic)
}
func (m *FollowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerRequest.Merge(m, src)
}
func (m *FollowerRequest) XXX_Size() int {
	return xxx_messageInfo_FollowerRequest.Size(m)
}
func (m *FollowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerRequest proto.InternalMessageInfo

func (m *FollowerRequest) GetGithubUsername() string {
	if m != nil {
		return m.GithubUsername
	}
	return ""
}

type FollowerResponse struct {
	FollowerList         []string `protobuf:"bytes,1,rep,name=follower_list,json=followerList,proto3" json:"follower_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowerResponse) Reset()         { *m = FollowerResponse{} }
func (m *FollowerResponse) String() string { return proto.CompactTextString(m) }
func (*FollowerResponse) ProtoMessage()    {}
func (*FollowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7664b366d7fb87ed, []int{1}
}

func (m *FollowerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerResponse.Unmarshal(m, b)
}
func (m *FollowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerResponse.Marshal(b, m, deterministic)
}
func (m *FollowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerResponse.Merge(m, src)
}
func (m *FollowerResponse) XXX_Size() int {
	return xxx_messageInfo_FollowerResponse.Size(m)
}
func (m *FollowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerResponse proto.InternalMessageInfo

func (m *FollowerResponse) GetFollowerList() []string {
	if m != nil {
		return m.FollowerList
	}
	return nil
}

func init() {
	proto.RegisterType((*FollowerRequest)(nil), "github.FollowerRequest")
	proto.RegisterType((*FollowerResponse)(nil), "github.FollowerResponse")
}

func init() { proto.RegisterFile("github.proto", fileDescriptor_7664b366d7fb87ed) }

var fileDescriptor_7664b366d7fb87ed = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xac, 0xb8, 0xf8,
	0xdd, 0xf2, 0x73, 0x72, 0xf2, 0xcb, 0x53, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0xd4, 0xb9, 0xf8, 0x21, 0x92, 0xf1, 0xa5, 0xc5, 0xa9, 0x45, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x7c, 0x10, 0xe1, 0x50, 0xa8, 0xa8, 0x92, 0x39, 0x97, 0x00, 0x42,
	0x6f, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x32, 0x17, 0x6f, 0x1a, 0x54, 0x2c, 0x3e, 0x27,
	0xb3, 0xb8, 0x44, 0x82, 0x51, 0x81, 0x59, 0x83, 0x33, 0x88, 0x07, 0x26, 0xe8, 0x93, 0x59, 0x5c,
	0x62, 0x14, 0xc2, 0xc5, 0xeb, 0x0e, 0x36, 0x2a, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8,
	0x99, 0x8b, 0xc7, 0x3d, 0xb5, 0x04, 0x66, 0x58, 0xb1, 0x90, 0xb8, 0x1e, 0xd4, 0xb1, 0x68, 0x6e,
	0x93, 0x92, 0xc0, 0x94, 0x80, 0x58, 0xac, 0xc4, 0xe0, 0xc4, 0x19, 0xc5, 0x0e, 0x91, 0x2c, 0x48,
	0x62, 0x03, 0x7b, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x28, 0x01, 0x31, 0x24, 0xf4, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GithubServiceClient is the client API for GithubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GithubServiceClient interface {
	GetFollowers(ctx context.Context, in *FollowerRequest, opts ...grpc.CallOption) (*FollowerResponse, error)
}

type githubServiceClient struct {
	cc *grpc.ClientConn
}

func NewGithubServiceClient(cc *grpc.ClientConn) GithubServiceClient {
	return &githubServiceClient{cc}
}

func (c *githubServiceClient) GetFollowers(ctx context.Context, in *FollowerRequest, opts ...grpc.CallOption) (*FollowerResponse, error) {
	out := new(FollowerResponse)
	err := c.cc.Invoke(ctx, "/github.GithubService/GetFollowers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubServiceServer is the server API for GithubService service.
type GithubServiceServer interface {
	GetFollowers(context.Context, *FollowerRequest) (*FollowerResponse, error)
}

// UnimplementedGithubServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGithubServiceServer struct {
}

func (*UnimplementedGithubServiceServer) GetFollowers(ctx context.Context, req *FollowerRequest) (*FollowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}

func RegisterGithubServiceServer(s *grpc.Server, srv GithubServiceServer) {
	s.RegisterService(&_GithubService_serviceDesc, srv)
}

func _GithubService_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServiceServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.GithubService/GetFollowers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServiceServer).GetFollowers(ctx, req.(*FollowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GithubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.GithubService",
	HandlerType: (*GithubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowers",
			Handler:    _GithubService_GetFollowers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.proto",
}
