# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: githubpb/github.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='githubpb/github.proto',
  package='github',
  syntax='proto3',
  serialized_options=b'Z\007githubp',
  serialized_pb=b'\n\x15githubpb/github.proto\x12\x06github\"*\n\x0f\x46ollowerRequest\x12\x17\n\x0fgithub_username\x18\x01 \x01(\t\")\n\x10\x46ollowerResponse\x12\x15\n\rfollower_list\x18\x01 \x03(\t2T\n\rGithubService\x12\x43\n\x0cGetFollowers\x12\x17.github.FollowerRequest\x1a\x18.github.FollowerResponse\"\x00\x42\tZ\x07githubpb\x06proto3'
)




_FOLLOWERREQUEST = _descriptor.Descriptor(
  name='FollowerRequest',
  full_name='github.FollowerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='github_username', full_name='github.FollowerRequest.github_username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=75,
)


_FOLLOWERRESPONSE = _descriptor.Descriptor(
  name='FollowerResponse',
  full_name='github.FollowerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='follower_list', full_name='github.FollowerResponse.follower_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['FollowerRequest'] = _FOLLOWERREQUEST
DESCRIPTOR.message_types_by_name['FollowerResponse'] = _FOLLOWERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FollowerRequest = _reflection.GeneratedProtocolMessageType('FollowerRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOWERREQUEST,
  '__module__' : 'githubpb.github_pb2'
  # @@protoc_insertion_point(class_scope:github.FollowerRequest)
  })
_sym_db.RegisterMessage(FollowerRequest)

FollowerResponse = _reflection.GeneratedProtocolMessageType('FollowerResponse', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOWERRESPONSE,
  '__module__' : 'githubpb.github_pb2'
  # @@protoc_insertion_point(class_scope:github.FollowerResponse)
  })
_sym_db.RegisterMessage(FollowerResponse)


DESCRIPTOR._options = None

_GITHUBSERVICE = _descriptor.ServiceDescriptor(
  name='GithubService',
  full_name='github.GithubService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=120,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFollowers',
    full_name='github.GithubService.GetFollowers',
    index=0,
    containing_service=None,
    input_type=_FOLLOWERREQUEST,
    output_type=_FOLLOWERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GITHUBSERVICE)

DESCRIPTOR.services_by_name['GithubService'] = _GITHUBSERVICE

# @@protoc_insertion_point(module_scope)
